export const BUSINESS_PROCESSES = {
  MMO_TRANSACTIONS: 'mmo_transactions',
  MFB_TRANSACTIONS: 'mfb_transactions',
  ATM_LOCATIONS: 'atm_locations',
  BANK_AGENTS_LOCATION: 'bank_agents_locations',
  PENSION_FUND_ADMIN: 'pension_fund_admin',
  INSURANCE: 'insurance',
  MFB_LOCATIONS: 'mfb_locations',
  CMB_LOCATIONS: 'cmb_locations',
  MORTGAGE_BANKS: 'mortgage_banks',
  DEVELOPMENT_FINANCE_INSTITUTION: 'development_finance_institution',
  MMO: 'mmo',
  BDC: 'bdc',
  SEC: 'sec',
  COMPLAINT_CATEGORY: 'complaint_category',
  COMPLAINT: 'complaint',
  FRAUD: 'fraud',
};
