version: '3.5'
services:
  nfsmaps-datawarehouse:
    container_name: nfsdatawarehouse
    restart: always
    build: .
    ports:
      - '1228:1228'
    links:
      - mongo
      - mysql
      - postgres
    # environment:
    #   - NODE_ENV=prod
  mongo:
    container_name: nfsmaps-mongo
    image: 'mongo:5'
    ports: 
      - '27017:27017'
  # mysql
  mysql:
    image: "mysql:5.7.37"
    container_name: "typeorm-mysql"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=Rasengan_123
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - mysql


   # postgres
  postgres:
    image: "mdillon/postgis:9.6"
    container_name: "typeorm-postgres"
    ports:
      - "5431:5432"
    env_file:
      - .env
    # environment:
      # POSTGRES_DB_PASSWORD: "Rasengan_123"

networks:
  external-net:
    external:
      name: external-net
  mysql:
    driver: bridge
      