version: '3'
services:
  nfsmaps:
    container_name: nfsdatawarehouse
    restart: always
    build: .
    ports:
      - '1228:1228'
    links:
      - mongo
      - mysql
      - postgres
  mongo:
    container_name: nfsmaps-mongo
    image: 'mongo:5'
    ports: 
      - '27017:27017'
  # mysql
  mysql:
    image: "mysql:5.7.37"
    container_name: "typeorm-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Rasengan_123"
      MYSQL_PASSWORD: "Rasengan_123"
      MYSQL_DATABASE: "utilityappdb"


   # postgres
  postgres:
    image: "mdillon/postgis:9.6"
    container_name: "typeorm-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "Rasengan_123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "cbn"
      